//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientFromVizitEurope.ServiceVizitEurope {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceVizitEurope.NightPricesServiceSoap")]
    public interface NightPricesServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUpdatedStopSales", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ClientFromVizitEurope.ServiceVizitEurope.stopsale[] GetUpdatedStopSales(System.DateTime updatedAfter);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUpdatedStopSales", ReplyAction="*")]
        System.Threading.Tasks.Task<ClientFromVizitEurope.ServiceVizitEurope.stopsale[]> GetUpdatedStopSalesAsync(System.DateTime updatedAfter);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUpdatedQuotes", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ClientFromVizitEurope.ServiceVizitEurope.quote[] GetUpdatedQuotes(System.DateTime updatedAfter);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUpdatedQuotes", ReplyAction="*")]
        System.Threading.Tasks.Task<ClientFromVizitEurope.ServiceVizitEurope.quote[]> GetUpdatedQuotesAsync(System.DateTime updatedAfter);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDeletedQuotes", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ClientFromVizitEurope.ServiceVizitEurope.quote[] GetDeletedQuotes(System.DateTime updatedAfter);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDeletedQuotes", ReplyAction="*")]
        System.Threading.Tasks.Task<ClientFromVizitEurope.ServiceVizitEurope.quote[]> GetDeletedQuotesAsync(System.DateTime updatedAfter);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDeletedStops", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ClientFromVizitEurope.ServiceVizitEurope.stopsale[] GetDeletedStops(System.DateTime updatedAfter);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDeletedStops", ReplyAction="*")]
        System.Threading.Tasks.Task<ClientFromVizitEurope.ServiceVizitEurope.stopsale[]> GetDeletedStopsAsync(System.DateTime updatedAfter);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DictionaryPansions", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ClientFromVizitEurope.ServiceVizitEurope.pansion[] DictionaryPansions();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DictionaryPansions", ReplyAction="*")]
        System.Threading.Tasks.Task<ClientFromVizitEurope.ServiceVizitEurope.pansion[]> DictionaryPansionsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DictionaryRoomTypes", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ClientFromVizitEurope.ServiceVizitEurope.roomtype[] DictionaryRoomTypes();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DictionaryRoomTypes", ReplyAction="*")]
        System.Threading.Tasks.Task<ClientFromVizitEurope.ServiceVizitEurope.roomtype[]> DictionaryRoomTypesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DictionaryRoomCategories", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ClientFromVizitEurope.ServiceVizitEurope.category[] DictionaryRoomCategories();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DictionaryRoomCategories", ReplyAction="*")]
        System.Threading.Tasks.Task<ClientFromVizitEurope.ServiceVizitEurope.category[]> DictionaryRoomCategoriesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DictionaryAccommodations", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ClientFromVizitEurope.ServiceVizitEurope.accmmodation[] DictionaryAccommodations();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DictionaryAccommodations", ReplyAction="*")]
        System.Threading.Tasks.Task<ClientFromVizitEurope.ServiceVizitEurope.accmmodation[]> DictionaryAccommodationsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DictionaryCountries", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ClientFromVizitEurope.ServiceVizitEurope.country[] DictionaryCountries();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DictionaryCountries", ReplyAction="*")]
        System.Threading.Tasks.Task<ClientFromVizitEurope.ServiceVizitEurope.country[]> DictionaryCountriesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DictionaryCities", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ClientFromVizitEurope.ServiceVizitEurope.city[] DictionaryCities(int countryId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DictionaryCities", ReplyAction="*")]
        System.Threading.Tasks.Task<ClientFromVizitEurope.ServiceVizitEurope.city[]> DictionaryCitiesAsync(int countryId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DictionaryHotels", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ClientFromVizitEurope.ServiceVizitEurope.hotel[] DictionaryHotels(int cityId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DictionaryHotels", ReplyAction="*")]
        System.Threading.Tasks.Task<ClientFromVizitEurope.ServiceVizitEurope.hotel[]> DictionaryHotelsAsync(int cityId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPrices", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ClientFromVizitEurope.ServiceVizitEurope.cost[] GetPrices(int cityId, int[] hotelIds, System.DateTime updatedAfter);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPrices", ReplyAction="*")]
        System.Threading.Tasks.Task<ClientFromVizitEurope.ServiceVizitEurope.cost[]> GetPricesAsync(int cityId, int[] hotelIds, System.DateTime updatedAfter);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDeletedPriceIds", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int[] GetDeletedPriceIds(int cityId, int[] hotelIds, System.DateTime updatedAfter);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDeletedPriceIds", ReplyAction="*")]
        System.Threading.Tasks.Task<int[]> GetDeletedPriceIdsAsync(int cityId, int[] hotelIds, System.DateTime updatedAfter);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetActualPriceIds", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int[] GetActualPriceIds(int cityId, int[] hotelIds);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetActualPriceIds", ReplyAction="*")]
        System.Threading.Tasks.Task<int[]> GetActualPriceIdsAsync(int cityId, int[] hotelIds);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class stopsale : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idField;
        
        private System.DateTime updatedField;
        
        private System.DateTime dateField;
        
        private int htField;
        
        private int rtField;
        
        private int rmField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime updated {
            get {
                return this.updatedField;
            }
            set {
                this.updatedField = value;
                this.RaisePropertyChanged("updated");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime date {
            get {
                return this.dateField;
            }
            set {
                this.dateField = value;
                this.RaisePropertyChanged("date");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int ht {
            get {
                return this.htField;
            }
            set {
                this.htField = value;
                this.RaisePropertyChanged("ht");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int rt {
            get {
                return this.rtField;
            }
            set {
                this.rtField = value;
                this.RaisePropertyChanged("rt");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int rm {
            get {
                return this.rmField;
            }
            set {
                this.rmField = value;
                this.RaisePropertyChanged("rm");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class cost : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idField;
        
        private string weekField;
        
        private int longminField;
        
        private int longmaxField;
        
        private System.DateTime updatedField;
        
        private System.DateTime dateField;
        
        private System.DateTime dateendField;
        
        private System.DateTime checkin_minField;
        
        private System.DateTime checkin_maxField;
        
        private int htField;
        
        private int pnField;
        
        private int rtField;
        
        private int accField;
        
        private int rmField;
        
        private decimal nettoField;
        
        private string rateField;
        
        private bool by_roomField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string week {
            get {
                return this.weekField;
            }
            set {
                this.weekField = value;
                this.RaisePropertyChanged("week");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int longmin {
            get {
                return this.longminField;
            }
            set {
                this.longminField = value;
                this.RaisePropertyChanged("longmin");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int longmax {
            get {
                return this.longmaxField;
            }
            set {
                this.longmaxField = value;
                this.RaisePropertyChanged("longmax");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime updated {
            get {
                return this.updatedField;
            }
            set {
                this.updatedField = value;
                this.RaisePropertyChanged("updated");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime date {
            get {
                return this.dateField;
            }
            set {
                this.dateField = value;
                this.RaisePropertyChanged("date");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime dateend {
            get {
                return this.dateendField;
            }
            set {
                this.dateendField = value;
                this.RaisePropertyChanged("dateend");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime checkin_min {
            get {
                return this.checkin_minField;
            }
            set {
                this.checkin_minField = value;
                this.RaisePropertyChanged("checkin_min");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime checkin_max {
            get {
                return this.checkin_maxField;
            }
            set {
                this.checkin_maxField = value;
                this.RaisePropertyChanged("checkin_max");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int ht {
            get {
                return this.htField;
            }
            set {
                this.htField = value;
                this.RaisePropertyChanged("ht");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int pn {
            get {
                return this.pnField;
            }
            set {
                this.pnField = value;
                this.RaisePropertyChanged("pn");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int rt {
            get {
                return this.rtField;
            }
            set {
                this.rtField = value;
                this.RaisePropertyChanged("rt");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int acc {
            get {
                return this.accField;
            }
            set {
                this.accField = value;
                this.RaisePropertyChanged("acc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int rm {
            get {
                return this.rmField;
            }
            set {
                this.rmField = value;
                this.RaisePropertyChanged("rm");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal netto {
            get {
                return this.nettoField;
            }
            set {
                this.nettoField = value;
                this.RaisePropertyChanged("netto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string rate {
            get {
                return this.rateField;
            }
            set {
                this.rateField = value;
                this.RaisePropertyChanged("rate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool by_room {
            get {
                return this.by_roomField;
            }
            set {
                this.by_roomField = value;
                this.RaisePropertyChanged("by_room");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class hotel : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idField;
        
        private string codeField;
        
        private string starsField;
        
        private string titleField;
        
        private System.DateTime updatedField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string stars {
            get {
                return this.starsField;
            }
            set {
                this.starsField = value;
                this.RaisePropertyChanged("stars");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
                this.RaisePropertyChanged("title");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime updated {
            get {
                return this.updatedField;
            }
            set {
                this.updatedField = value;
                this.RaisePropertyChanged("updated");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class city : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idField;
        
        private string codeField;
        
        private string titleField;
        
        private System.DateTime updatedField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
                this.RaisePropertyChanged("title");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime updated {
            get {
                return this.updatedField;
            }
            set {
                this.updatedField = value;
                this.RaisePropertyChanged("updated");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class country : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idField;
        
        private string codeField;
        
        private string titleField;
        
        private System.DateTime updatedField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
                this.RaisePropertyChanged("title");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime updated {
            get {
                return this.updatedField;
            }
            set {
                this.updatedField = value;
                this.RaisePropertyChanged("updated");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class accmmodation : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idField;
        
        private string codeField;
        
        private string titleField;
        
        private System.DateTime updatedField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
                this.RaisePropertyChanged("title");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime updated {
            get {
                return this.updatedField;
            }
            set {
                this.updatedField = value;
                this.RaisePropertyChanged("updated");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class category : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idField;
        
        private string codeField;
        
        private string titleField;
        
        private System.DateTime updatedField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
                this.RaisePropertyChanged("title");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime updated {
            get {
                return this.updatedField;
            }
            set {
                this.updatedField = value;
                this.RaisePropertyChanged("updated");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class roomtype : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idField;
        
        private string codeField;
        
        private string titleField;
        
        private System.DateTime updatedField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
                this.RaisePropertyChanged("title");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime updated {
            get {
                return this.updatedField;
            }
            set {
                this.updatedField = value;
                this.RaisePropertyChanged("updated");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class pansion : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idField;
        
        private string codeField;
        
        private string titleField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
                this.RaisePropertyChanged("title");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class quote : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idField;
        
        private System.DateTime updatedField;
        
        private System.DateTime dateField;
        
        private int htField;
        
        private int rtField;
        
        private int busyField;
        
        private int placesField;
        
        private int releaseField;
        
        private int rmField;
        
        private bool by_roomField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime updated {
            get {
                return this.updatedField;
            }
            set {
                this.updatedField = value;
                this.RaisePropertyChanged("updated");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime date {
            get {
                return this.dateField;
            }
            set {
                this.dateField = value;
                this.RaisePropertyChanged("date");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int ht {
            get {
                return this.htField;
            }
            set {
                this.htField = value;
                this.RaisePropertyChanged("ht");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int rt {
            get {
                return this.rtField;
            }
            set {
                this.rtField = value;
                this.RaisePropertyChanged("rt");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int busy {
            get {
                return this.busyField;
            }
            set {
                this.busyField = value;
                this.RaisePropertyChanged("busy");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int places {
            get {
                return this.placesField;
            }
            set {
                this.placesField = value;
                this.RaisePropertyChanged("places");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int release {
            get {
                return this.releaseField;
            }
            set {
                this.releaseField = value;
                this.RaisePropertyChanged("release");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int rm {
            get {
                return this.rmField;
            }
            set {
                this.rmField = value;
                this.RaisePropertyChanged("rm");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool by_room {
            get {
                return this.by_roomField;
            }
            set {
                this.by_roomField = value;
                this.RaisePropertyChanged("by_room");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface NightPricesServiceSoapChannel : ClientFromVizitEurope.ServiceVizitEurope.NightPricesServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class NightPricesServiceSoapClient : System.ServiceModel.ClientBase<ClientFromVizitEurope.ServiceVizitEurope.NightPricesServiceSoap>, ClientFromVizitEurope.ServiceVizitEurope.NightPricesServiceSoap {
        
        public NightPricesServiceSoapClient() {
        }
        
        public NightPricesServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public NightPricesServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NightPricesServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NightPricesServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ClientFromVizitEurope.ServiceVizitEurope.stopsale[] GetUpdatedStopSales(System.DateTime updatedAfter) {
            return base.Channel.GetUpdatedStopSales(updatedAfter);
        }
        
        public System.Threading.Tasks.Task<ClientFromVizitEurope.ServiceVizitEurope.stopsale[]> GetUpdatedStopSalesAsync(System.DateTime updatedAfter) {
            return base.Channel.GetUpdatedStopSalesAsync(updatedAfter);
        }
        
        public ClientFromVizitEurope.ServiceVizitEurope.quote[] GetUpdatedQuotes(System.DateTime updatedAfter) {
            return base.Channel.GetUpdatedQuotes(updatedAfter);
        }
        
        public System.Threading.Tasks.Task<ClientFromVizitEurope.ServiceVizitEurope.quote[]> GetUpdatedQuotesAsync(System.DateTime updatedAfter) {
            return base.Channel.GetUpdatedQuotesAsync(updatedAfter);
        }
        
        public ClientFromVizitEurope.ServiceVizitEurope.quote[] GetDeletedQuotes(System.DateTime updatedAfter) {
            return base.Channel.GetDeletedQuotes(updatedAfter);
        }
        
        public System.Threading.Tasks.Task<ClientFromVizitEurope.ServiceVizitEurope.quote[]> GetDeletedQuotesAsync(System.DateTime updatedAfter) {
            return base.Channel.GetDeletedQuotesAsync(updatedAfter);
        }
        
        public ClientFromVizitEurope.ServiceVizitEurope.stopsale[] GetDeletedStops(System.DateTime updatedAfter) {
            return base.Channel.GetDeletedStops(updatedAfter);
        }
        
        public System.Threading.Tasks.Task<ClientFromVizitEurope.ServiceVizitEurope.stopsale[]> GetDeletedStopsAsync(System.DateTime updatedAfter) {
            return base.Channel.GetDeletedStopsAsync(updatedAfter);
        }
        
        public ClientFromVizitEurope.ServiceVizitEurope.pansion[] DictionaryPansions() {
            return base.Channel.DictionaryPansions();
        }
        
        public System.Threading.Tasks.Task<ClientFromVizitEurope.ServiceVizitEurope.pansion[]> DictionaryPansionsAsync() {
            return base.Channel.DictionaryPansionsAsync();
        }
        
        public ClientFromVizitEurope.ServiceVizitEurope.roomtype[] DictionaryRoomTypes() {
            return base.Channel.DictionaryRoomTypes();
        }
        
        public System.Threading.Tasks.Task<ClientFromVizitEurope.ServiceVizitEurope.roomtype[]> DictionaryRoomTypesAsync() {
            return base.Channel.DictionaryRoomTypesAsync();
        }
        
        public ClientFromVizitEurope.ServiceVizitEurope.category[] DictionaryRoomCategories() {
            return base.Channel.DictionaryRoomCategories();
        }
        
        public System.Threading.Tasks.Task<ClientFromVizitEurope.ServiceVizitEurope.category[]> DictionaryRoomCategoriesAsync() {
            return base.Channel.DictionaryRoomCategoriesAsync();
        }
        
        public ClientFromVizitEurope.ServiceVizitEurope.accmmodation[] DictionaryAccommodations() {
            return base.Channel.DictionaryAccommodations();
        }
        
        public System.Threading.Tasks.Task<ClientFromVizitEurope.ServiceVizitEurope.accmmodation[]> DictionaryAccommodationsAsync() {
            return base.Channel.DictionaryAccommodationsAsync();
        }
        
        public ClientFromVizitEurope.ServiceVizitEurope.country[] DictionaryCountries() {
            return base.Channel.DictionaryCountries();
        }
        
        public System.Threading.Tasks.Task<ClientFromVizitEurope.ServiceVizitEurope.country[]> DictionaryCountriesAsync() {
            return base.Channel.DictionaryCountriesAsync();
        }
        
        public ClientFromVizitEurope.ServiceVizitEurope.city[] DictionaryCities(int countryId) {
            return base.Channel.DictionaryCities(countryId);
        }
        
        public System.Threading.Tasks.Task<ClientFromVizitEurope.ServiceVizitEurope.city[]> DictionaryCitiesAsync(int countryId) {
            return base.Channel.DictionaryCitiesAsync(countryId);
        }
        
        public ClientFromVizitEurope.ServiceVizitEurope.hotel[] DictionaryHotels(int cityId) {
            return base.Channel.DictionaryHotels(cityId);
        }
        
        public System.Threading.Tasks.Task<ClientFromVizitEurope.ServiceVizitEurope.hotel[]> DictionaryHotelsAsync(int cityId) {
            return base.Channel.DictionaryHotelsAsync(cityId);
        }
        
        public ClientFromVizitEurope.ServiceVizitEurope.cost[] GetPrices(int cityId, int[] hotelIds, System.DateTime updatedAfter) {
            return base.Channel.GetPrices(cityId, hotelIds, updatedAfter);
        }
        
        public System.Threading.Tasks.Task<ClientFromVizitEurope.ServiceVizitEurope.cost[]> GetPricesAsync(int cityId, int[] hotelIds, System.DateTime updatedAfter) {
            return base.Channel.GetPricesAsync(cityId, hotelIds, updatedAfter);
        }
        
        public int[] GetDeletedPriceIds(int cityId, int[] hotelIds, System.DateTime updatedAfter) {
            return base.Channel.GetDeletedPriceIds(cityId, hotelIds, updatedAfter);
        }
        
        public System.Threading.Tasks.Task<int[]> GetDeletedPriceIdsAsync(int cityId, int[] hotelIds, System.DateTime updatedAfter) {
            return base.Channel.GetDeletedPriceIdsAsync(cityId, hotelIds, updatedAfter);
        }
        
        public int[] GetActualPriceIds(int cityId, int[] hotelIds) {
            return base.Channel.GetActualPriceIds(cityId, hotelIds);
        }
        
        public System.Threading.Tasks.Task<int[]> GetActualPriceIdsAsync(int cityId, int[] hotelIds) {
            return base.Channel.GetActualPriceIdsAsync(cityId, hotelIds);
        }
    }
}
